app:
  baseUrl: http://localhost

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: ${BACKEND_LISTEN_PORT}
  cors:
    origin: ['http://localhost', 'http://nginx']
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
